import test from "node:test";
import assert from "node:assert/strict";
import { BrowserBridge } from "../src/browserBridge.js";

function connectedBridge(now=()=>Date.now()){const bridge=new BrowserBridge({bridgeToken:"desktop-secret",now});bridge.heartbeat("desktop-secret");return bridge;}
function token(bridge){return bridge.issueAgentToken({actor:"Codex",provider:"codex"});}

test("agent open queues a visible desktop command and grants origin after verified completion",async()=>{const bridge=connectedBridge();const response=bridge.request({token:token(bridge),action:"open",payload:{url:"https://example.com/a"}});const command=bridge.nextCommand("desktop-secret");assert.equal(command.action,"open");assert.equal(command.actor,"Codex");bridge.complete("desktop-secret",command.id,{ok:true,url:"https://example.com/a"});assert.equal((await response).ok,true);assert.equal(bridge.status().share.origin,"https://example.com");});
test("forged tokens cannot open the browser",async()=>{const bridge=connectedBridge();await assert.rejects(bridge.request({token:"forged",action:"open",payload:{url:"https://example.com"}}),/ajan yetkisi/);});
test("open requests are rate limited per provider",async()=>{let clock=100_000;const bridge=connectedBridge(()=>clock);const first=bridge.request({token:token(bridge),action:"open",payload:{url:"https://one.example"}});const command=bridge.nextCommand("desktop-secret");bridge.complete("desktop-secret",command.id,{url:"https://one.example"});await first;bridge.stop();clock+=1000;await assert.rejects(bridge.request({token:token(bridge),action:"open",payload:{url:"https://two.example"}}),/hız sınırı/);});
test("same-origin open is deduplicated without moving the panel",async()=>{const bridge=connectedBridge();bridge.grant({origin:"https://example.com"});const result=await bridge.request({token:token(bridge),action:"open",payload:{url:"https://example.com/next"}});assert.equal(result.deduplicated,true);assert.equal(bridge.nextCommand("desktop-secret"),null);});
test("explicit agent task queues ordinary interaction without a share button",async()=>{const bridge=connectedBridge();bridge.grant({origin:"https://example.com"});const response=bridge.request({token:token(bridge),action:"type",payload:{elementId:"e1",text:"query"}});const command=bridge.nextCommand("desktop-secret");assert.equal(command.action,"type");bridge.complete("desktop-secret",command.id,{ok:true,url:"https://example.com"});assert.equal((await response).ok,true);});
test("first snapshot automatically attaches the active tab",async()=>{const bridge=connectedBridge();const response=bridge.request({token:token(bridge),action:"snapshot",payload:{}});const command=bridge.nextCommand("desktop-secret");assert.equal(command.origin,"");bridge.complete("desktop-secret",command.id,{title:"Example",url:"https://example.com/page",origin:"https://example.com",text:"hello",elements:[]});assert.equal((await response).title,"Example");assert.equal(bridge.status().share.origin,"https://example.com");});
test("origin change during open is rejected and not shared",async()=>{const bridge=connectedBridge();const response=bridge.request({token:token(bridge),action:"open",payload:{url:"https://example.com"}});const command=bridge.nextCommand("desktop-secret");bridge.complete("desktop-secret",command.id,{url:"https://evil.example"});await assert.rejects(response,/Origin/);assert.equal(bridge.status().shared,false);});
// Regresyon: arayüz durum bilgisini saniyede bir sorar. activeShare() paylaşım
// YOKKEN de stop() çağırdığı için, işlenmekte olan open komutu arayüzün kendi
// sorgusuyla iptal ediliyordu; paylaşım ancak açılış bitince oluştuğundan ilk
// açılış gerçek uygulamada hiç başarılı olamıyordu.
test("status polling does not cancel an in-flight open",async()=>{const bridge=connectedBridge();const response=bridge.request({token:token(bridge),action:"open",payload:{url:"https://example.com/a"}});const command=bridge.nextCommand("desktop-secret");bridge.status();bridge.status();assert.equal(bridge.status().opening,true);bridge.complete("desktop-secret",command.id,{ok:true,url:"https://example.com/a"});assert.equal((await response).ok,true);assert.equal(bridge.status().share.origin,"https://example.com");});
