import crypto from "node:crypto";
import { redactBrowserSnapshot, validateBrowserUrl } from "./browserPolicy.js";

export class BrowserBridge {
  constructor({ bridgeToken="", now=()=>Date.now() }={}) { this.bridgeToken=bridgeToken; this.now=now; this.commands=[]; this.pending=new Map(); this.agentTokens=new Map(); this.share=null; this.connectedAt=0; this.active=null; this.approval=null; this.events=[]; this.openHistory=new Map(); }
  record(type,detail=""){this.events.push({type,detail:String(detail).slice(0,200),at:this.now()});if(this.events.length>30)this.events.shift();}
  authenticateBridge(token){const expected=Buffer.from(this.bridgeToken);const actual=Buffer.from(String(token||""));return Boolean(expected.length&&expected.length===actual.length&&crypto.timingSafeEqual(expected,actual));}
  heartbeat(token){if(!this.authenticateBridge(token))return false;this.connectedAt=this.now();return true;}
  issueAgentToken({actor,provider,ttlMs=120_000}){const token=crypto.randomBytes(32).toString("base64url");this.agentTokens.set(token,{actor:String(actor).slice(0,80),provider:String(provider).slice(0,40),expiresAt:this.now()+ttlMs,remaining:10});return token;}
  consumeAgentToken(token){const key=String(token||"");const grant=this.agentTokens.get(key);if(!grant||grant.expiresAt<=this.now()||grant.remaining<=0){this.agentTokens.delete(key);return null;}grant.remaining-=1;return grant;}
  grant({origin,durationMs=60_000,actor="",provider=""}){const checked=validateBrowserUrl(origin);if(!checked.ok)throw new Error(checked.reason);this.stop("Yeni tarayıcı paylaşımı başlatıldı");this.share={origin:new URL(checked.url).origin,expiresAt:this.now()+Math.min(Math.max(Number(durationMs)||0,5000),300_000),actor:String(actor).slice(0,80),provider:String(provider).slice(0,40)};this.record("shared",this.share.origin);return this.share;}
  activeShare(){if(!this.share||this.share.expiresAt<=this.now())this.stop("Tarayıcı paylaşım izni sona erdi");return this.share;}
  isConnected(){return this.connectedAt>this.now()-3000;}
  status(){const share=this.activeShare();return{connected:this.isConnected(),shared:Boolean(share),opening:this.active?.action==="open",share,active:this.active,approval:this.approval&&{id:this.approval.id,actor:this.approval.actor,action:this.approval.action,summary:this.approval.summary},events:this.events.slice(-8)};}
  checkOpenRate(agent,origin){const now=this.now();if(this.share?.origin===origin&&this.share.expiresAt>now)return false;const history=(this.openHistory.get(agent.provider)||[]).filter((at)=>at>now-300_000);if(history.some((at)=>at>now-10_000)||history.length>=5){const error=new Error("Tarayıcı açma hız sınırı aşıldı");error.code="RATE_LIMIT";throw error;}history.push(now);this.openHistory.set(agent.provider,history);return true;}
  request({token,action="snapshot",payload={}}){const agent=this.consumeAgentToken(token);if(!agent)return Promise.reject(Object.assign(new Error("Geçersiz veya süresi dolmuş ajan yetkisi"),{code:"AUTH"}));if(!["open","snapshot","navigate","click","type"].includes(action))return Promise.reject(Object.assign(new Error("Desteklenmeyen tarayıcı eylemi"),{code:"POLICY"}));if(!this.isConnected())return Promise.reject(Object.assign(new Error("Masaüstü tarayıcısı bağlı değil"),{code:"BRIDGE"}));if(this.pending.size)return Promise.reject(Object.assign(new Error("Tarayıcı başka bir ajan komutunu işliyor"),{code:"BUSY"}));let share=this.activeShare();
    if(action==="open"){const checked=validateBrowserUrl(payload.url);if(!checked.ok)return Promise.reject(Object.assign(new Error(checked.reason),{code:"POLICY"}));const origin=new URL(checked.url).origin;try{if(!this.checkOpenRate(agent,origin))return Promise.resolve({ok:true,deduplicated:true,origin});}catch(error){return Promise.reject(error);}this.share=null;payload={url:checked.url};return this.enqueue({agent,action,payload,origin,expiresAt:this.now()+60_000,needsApproval:false});}
    if(!share)return Promise.reject(new Error("Kullanıcı bu siteyi ajanla paylaşmadı"));if(action==="navigate"){const checked=validateBrowserUrl(payload.url);if(!checked.ok)return Promise.reject(Object.assign(new Error(checked.reason),{code:"POLICY"}));if(new URL(checked.url).origin!==share.origin)return Promise.reject(new Error("Farklı origin için yeni open isteği gerekir"));payload={url:checked.url};}if(action==="click")payload={elementId:String(payload.elementId||"").slice(0,80)};if(action==="type")payload={elementId:String(payload.elementId||"").slice(0,80),text:String(payload.text||"").slice(0,2000)};return this.enqueue({agent,action,payload,origin:share.origin,expiresAt:share.expiresAt,needsApproval:action!=="snapshot"});}
  enqueue({agent,action,payload,origin,expiresAt,needsApproval}){const id=crypto.randomUUID();this.active={id,actor:agent.actor,provider:agent.provider,action,startedAt:this.now()};if(needsApproval)this.approval={id,actor:agent.actor,action,summary:action==="navigate"?payload.url:`${payload.elementId} hedefi`};else this.commands.push({id,action,payload,origin,actor:agent.actor,provider:agent.provider,expiresAt});this.record(`${action}-requested`,agent.provider);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>this.fail(id,"Tarayıcı komutu zaman aşımına uğradı"),30_000);this.pending.set(id,{resolve,reject,timer,action,origin,payload,agent});});}
  approve(id,approved){if(!this.approval||this.approval.id!==id)return false;const pending=this.pending.get(id);this.approval=null;if(!approved){this.fail(id,"Kullanıcı tarayıcı eylemini reddetti");return true;}const share=this.activeShare();if(!pending||!share||share.origin!==pending.origin){this.fail(id,"Paylaşılan origin değişti");return true;}this.commands.push({id,action:pending.action,payload:pending.payload,origin:pending.origin,expiresAt:share.expiresAt});this.record(`${pending.action}-approved`);return true;}
  nextCommand(token){if(!this.heartbeat(token))return undefined;return this.commands.shift()||null;}
  complete(token,id,result,error){if(!this.authenticateBridge(token))return false;const pending=this.pending.get(id);if(!pending)return false;clearTimeout(pending.timer);this.pending.delete(id);const action=pending.action;this.active=null;this.approval=null;if(error){this.record(`${action}-failed`);pending.reject(new Error(String(error)));}else{if(action==="open"){const actual=validateBrowserUrl(result?.url);if(!actual.ok||new URL(actual.url).origin!==pending.origin){pending.reject(new Error("Origin açılış sırasında değişti"));this.record("open-failed");return true;}this.share={origin:pending.origin,expiresAt:this.now()+60_000,actor:pending.agent.actor,provider:pending.agent.provider};this.record("shared",pending.origin);}this.record(`${action}-completed`);pending.resolve(action==="snapshot"?redactBrowserSnapshot(result):result);}return true;}
  fail(id,reason){const pending=this.pending.get(id);if(!pending)return;clearTimeout(pending.timer);this.pending.delete(id);this.commands=this.commands.filter((item)=>item.id!==id);this.active=null;this.approval=null;this.record(`${pending.action}-failed`);pending.reject(new Error(reason));}
  stop(reason="Tarayıcı paylaşımı durduruldu"){const active=Boolean(this.share||this.pending.size);this.share=null;this.commands.length=0;this.approval=null;for(const id of [...this.pending.keys()])this.fail(id,reason);this.active=null;if(active)this.record("stopped",reason);}
}
